include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style / correctness
    always_declare_return_types: true
    avoid_dynamic_calls: true
    avoid_print: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    always_put_required_named_parameters_first: false
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    unnecessary_this: true
    use_key_in_widget_constructors: true
    use_super_parameters: true
    require_trailing_commas: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_use_of_visible_for_testing_member: warning
    todo: ignore
